'use server'

import { createClient } from '@/lib/supabase/server'
import { requireRole } from '@/lib/auth'
import { revalidatePath, revalidateTag } from 'next/cache'
import { logAudit, actorFromProfile } from '@/lib/audit-log'
import type { Coach, Member } from '@/types'

// Coaches get pushed to the device the same way members do (see
// pushNewMembersToDevice in members.ts) — device_number is a coach-only PIN
// namespace starting at 10000 (see supabase/coach_device_push.sql) so it
// never collides with a member_id. Pri=0 in the device command (normal
// user) — coaches get no elevated device access, this is purely so their
// name shows up on the device and their fingerprint can be enrolled there.
async function pushCoachToDevice(deviceNumber: number | null, name: string, requestedBy?: string): Promise<void> {
  if (deviceNumber == null) return
  try {
    const supabase = await createClient()
    await supabase.from('adms_commands').insert({
      operation: 'enroll',
      member_id: deviceNumber,
      full_name: name,
      requested_by: requestedBy ?? null,
    })
  } catch (err) {
    console.error('Auto-push coach to device failed:', err)
  }
}

export async function getCoaches(): Promise<Coach[]> {
  try {
    const supabase = await createClient()

    const { data, error } = await supabase
      .from('coaches')
      .select('*')
      .eq('is_active', true)
      .order('name', { ascending: true })

    if (error) throw error

    return (data ?? []) as Coach[]
  } catch (err) {
    console.error('getCoaches error:', err)
    return []
  }
}

export async function createCoach(data: FormData): Promise<{ error?: string }> {
  try {
    const profile = await requireRole(['admin', 'receptionist'])
    const supabase = await createClient()

    // coach_id is generated by a DB sequence default (see security_hardening.sql)
    const payload: Record<string, unknown> = {
      name: data.get('name') as string,
      mobile: data.get('mobile') as string,
      is_active: true,
    }

    const email = data.get('email') as string | null
    if (email) payload.email = email

    const specialization = data.get('specialization') as string | null
    if (specialization) payload.specialization = specialization

    const { data: inserted, error } = await supabase
      .from('coaches')
      .insert(payload)
      .select('id, device_number, name')
      .single()

    if (error) throw error

    const insertedRow = inserted as { id: string; device_number: number | null; name: string } | null
    if (insertedRow) {
      await pushCoachToDevice(insertedRow.device_number, insertedRow.name, profile.user_id)
    }

    await logAudit(actorFromProfile(profile), 'create', 'coach', insertedRow?.id ?? null, insertedRow?.name ?? (payload.name as string), {
      mobile: payload.mobile, specialization: payload.specialization,
    })

    revalidateTag('coaches', {})
    revalidatePath('/coaches')
    return {}
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { error: message }
  }
}

export async function updateCoach(
  id: string,
  data: FormData
): Promise<{ error?: string }> {
  try {
    const profile = await requireRole(['admin', 'receptionist'])
    const supabase = await createClient()

    const payload: Record<string, unknown> = {}

    const fields = ['name', 'mobile', 'email', 'specialization']
    for (const field of fields) {
      const value = data.get(field) as string | null
      if (value !== null && value !== '') {
        payload[field] = value
      }
    }

    const isActive = data.get('is_active')
    if (isActive !== null) {
      payload.is_active = isActive === 'true' || isActive === '1'
    }

    // The device stores name against PIN — same reasoning as members'
    // updateMember: without this, correcting a coach's name here would
    // update the CRM but leave the machine showing the old name indefinitely.
    const { data: current } = await supabase.from('coaches').select('device_number, name').eq('id', id).single()
    const currentRow = current as { device_number: number | null; name: string } | null
    const nameChanged = typeof payload.name === 'string' && currentRow && payload.name !== currentRow.name

    const { error } = await supabase.from('coaches').update(payload).eq('id', id)

    if (error) throw error

    if (nameChanged && currentRow) {
      await pushCoachToDevice(currentRow.device_number, payload.name as string, profile.user_id)
    }

    await logAudit(actorFromProfile(profile), 'update', 'coach', id, (payload.name as string | undefined) ?? currentRow?.name ?? null, {
      changed_fields: Object.keys(payload),
    })

    revalidateTag('coaches', {})
    revalidatePath('/coaches')
    return {}
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { error: message }
  }
}

export async function getCoachMembers(coachId: string): Promise<Member[]> {
  try {
    const supabase = await createClient()

    const { data, error } = await supabase
      .from('members')
      .select(`
        *,
        coach_members!inner(coach_id)
      `)
      .eq('coach_members.coach_id', coachId)

    if (error) throw error

    return (data ?? []) as unknown as Member[]
  } catch (err) {
    console.error('getCoachMembers error:', err)
    return []
  }
}

export async function assignMember(
  coachId: string,
  memberId: string
): Promise<{ error?: string }> {
  try {
    const profile = await requireRole(['admin', 'receptionist'])
    const supabase = await createClient()

    const { error } = await supabase
      .from('coach_members')
      .upsert({ coach_id: coachId, member_id: memberId }, { onConflict: 'coach_id,member_id', ignoreDuplicates: true })

    if (error) throw error

    await logAudit(actorFromProfile(profile), 'create', 'coach_assignment', `${coachId}:${memberId}`, null, { coach_id: coachId, member_id: memberId })

    revalidateTag('coaches', {})
    revalidatePath('/coaches')
    return {}
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { error: message }
  }
}

export async function unassignMember(
  coachId: string,
  memberId: string
): Promise<{ error?: string }> {
  try {
    const profile = await requireRole(['admin', 'receptionist'])
    const supabase = await createClient()

    const { error } = await supabase
      .from('coach_members')
      .delete()
      .eq('coach_id', coachId)
      .eq('member_id', memberId)

    if (error) throw error

    await logAudit(actorFromProfile(profile), 'delete', 'coach_assignment', `${coachId}:${memberId}`, null, { coach_id: coachId, member_id: memberId })

    revalidateTag('coaches', {})
    revalidatePath('/coaches')
    return {}
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    return { error: message }
  }
}

// Called by TableRealtimeRefresh whenever it detects any change to coaches
// or pt_plans, regardless of source — see revalidatePaymentsData (payments.ts)
// for the reasoning.
export async function revalidateCoachesData(): Promise<void> {
  revalidateTag('coaches', {})
  revalidatePath('/coaches')
}
